# Generated by Django 4.2.26 on 2025-11-30 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('muscle_group', models.CharField(blank=True, help_text='e.g. Chest, Legs, Full Body', max_length=50)),
                ('equipment', models.CharField(blank=True, help_text='e.g. None, Dumbbells, Resistance Band', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('total_time_minutes', models.IntegerField(blank=True, help_text='Approximate time in minutes', null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('category', models.CharField(choices=[('cardio', 'Cardio'), ('full_body_strength', 'Full Body Strength'), ('upper_body_strength', 'Upper Body Strength'), ('lower_body_strength', 'Lower Body Strength'), ('mobility', 'Mobility / Stretching'), ('bodyweight', 'Bodyweight Only')], default='cardio', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('sets', models.PositiveIntegerField(blank=True, null=True)),
                ('reps', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='For timed exercises like planks, in seconds', null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.workout')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('workout', 'exercise', 'order')},
            },
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(related_name='workouts', through='tracker.WorkoutExercise', to='tracker.exercise'),
        ),
    ]
