# Generated by Django 4.2.26 on 2025-11-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to a video explaining or demonstrating this workout.'),
        ),
    ]
