# Generated by Django 4.2.26 on 2025-11-30 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0002_workout_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Total sleep for the night in hours, e.g. 7.5', max_digits=4, null=True)),
                ('fasting_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Hours fasted since last meal', max_digits=4, null=True)),
                ('calories', models.IntegerField(blank=True, help_text='Estimated total calories for the day', null=True)),
                ('workout_completed', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, help_text='Optional: how you felt, steps, etc.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(blank=True, help_text='Workout you followed today (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_logs', to='tracker.workout')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
