# Generated by Django 4.2.26 on 2025-11-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, help_text='Name shown on your profile and leaderboards.', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If public, others can see your stats and you can appear on leaderboards.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Optional profile picture.', null=True, upload_to='profile_photos/'),
        ),
    ]
