# Generated by Django 4.2.26 on 2025-12-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_profile_display_name_profile_is_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailylog',
            name='workout',
        ),
        migrations.AddField(
            model_name='dailylog',
            name='workouts',
            field=models.ManyToManyField(blank=True, help_text='Workouts you followed today (you can choose more than one)', related_name='daily_logs', to='tracker.workout'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='workout_completed',
            field=models.BooleanField(default=False, help_text='Tick if you completed your planned workout(s) today'),
        ),
    ]
