# Generated by Django 4.2.26 on 2025-12-01 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_dailylog_workout_dailylog_workouts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailylog',
            name='workouts',
        ),
        migrations.AddField(
            model_name='dailylog',
            name='workout',
            field=models.ForeignKey(blank=True, help_text='Workout you followed today (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_logs', to='tracker.workout'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='workout_completed',
            field=models.BooleanField(default=False),
        ),
    ]
