# Generated by Django 4.2.26 on 2025-12-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_remove_dailylog_workouts_dailylog_workout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='workouts',
            field=models.ManyToManyField(blank=True, help_text='All workouts you did today (if any)', related_name='daily_logs_multi', to='tracker.workout'),
        ),
    ]
